# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: amchamay
    role: Maintain
  - member: santiago
    role: Maintain
  - member: bokoepf
    role: Maintain
  - member: shtople
    role: Maintain
  - member: t-akolluri
    role: Maintain
  - team: ProjectRomac4d3b8d42a
    role: Write
